services:
  - type: web
    name: social-media-downloader
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: social-media-downloader
          property: port
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    rootDir: .
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1