services:
  - type: web
    name: social-media-downloader
    env: node
    plan: free
    buildCommand: |
      npm install
      pip3 install --upgrade yt-dlp
      yt-dlp --version
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: social-media-downloader
          property: port
      - key: PATH
        value: /opt/render/project/src/.venv/bin:/usr/local/bin:/usr/bin:/bin
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    rootDir: .
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1